Fix rest routes identification
yakamara/redaxo_yform pull request #1233
Opened 2022-01-20 10:22 UTC by jganthaler

Hatte das Problem, dass wenn 2 Routen mit dem gleichen substring beginnen (z.B /foo und /foo-bar) beide gematcht werden und letztere nicht mehr funktioniert. 
Außerdem funktionierte die Erkennung der Route nicht, wenn die Redaxo Installation sich in einem Unterordner befindet. Habe diesen base ordner Teil jetzt einfach aus dem current path entfernt und jetzt funktioniert es auch in diesem Fall.

2022-01-26 22:04 UTC, dergel commented
Ich würde das gerne trennen.. erstmal, dass die Routen sich nicht überschreiben. YRewrite würde ich gerne komplett draußen lassen.

2023-02-28 21:20 UTC, alxndr-w requested changes

2023-02-28 21:20 UTC, alxndr-w commented on plugins/rest/lib/rest.php
> +            }
```suggestion
                $currentPath = str_replace($_SERVER['BASE'], '', $url['path']);
```

2023-03-09 11:03 UTC, dergel commented
Habe das verändert einbauen müssen, da sonst die Relationsauflösungen und Felder nicht mehr funktioniert hätten. Die Abfrage nach YRewrite für die Optimierung in Unterordnern habe ich doch mit reingenommen. Danke

2023-03-09 11:03 UTC, closed without merging