Fehler auslesen hinzugefügt
yakamara/redaxo_yform pull request #955
Opened 2020-10-28 11:07 UTC by TobiasKrais

2020-10-29 11:59 UTC, dergel commented
Danke f+r den PR..  Ich verstehe was du damit meinst. aber ich denke, da müsste noch etwas mehr Info rein .. Also, vielleicht der komplette PHP Code der YForm für den Versand mit getForm() und so. Dann ist das leichter zu verstehen. Ok für dich ? Willst du das nachtragen ?

2020-10-29 12:38 UTC, TobiasKrais commented
OK, der Teil des Formulares ist eigentlich uninteressant. Es geht einfach nur darum herauszufinden, ob das Formular einen Fehler (Warning) anzeigt oder nicht.

Hintergrund: Ich habe ein [Suchformular mit YForm](https://github.com/TobiasKrais/d2u_helper/blob/master/modules/14/1/output.php) geschrieben. Die Suche soll nur ausgelöst werden, wenn die Spamprüfung nicht anschlägt. Dazu prüfe ich, ob im Formular ein Fehler.

Wie sollte die Anpassung der Doku deiner Meinung nach aussehen, damit es jeder versteht?

2020-10-29 20:12 UTC, dergel commented
Ich würde das komplette php script mit new yform .... getForm() aufschreiben, in der einfachsten form, z.b. nur mit einem textfeld name .. und dahinter dann wie man prüft, ob das Formular erfolgreich abgeschickt wurde. Dann würde ich nicht auf warnings gehen, sondern eher auf $this->objparams['actions_executed'] ..

2020-11-16 07:21 UTC, TobiasKrais commented
Vielleicht wäre es sogar noch besser für jeden der objectparams eine kurze Beschreibung bereitzustellen.

2020-11-16 08:10 UTC, alxndr-w commented
@TobiasKrais nur zu. Es gibt offene issues dazu im alten docs-Repo.

2020-11-21 20:11 UTC, TobiasKrais commented
OK. Titel  des PR geändert. Jetzt gibt es ein Beispiel zum auslesen der Objparams und eine Doku der Objparams selbst. Allerdings kenne ich nicht die Bedeutung aller Objparams. Grundsatzfrage: geht das so in die Richtige Richtung? Falls ja, kann mir jemand bei der Doku der Objparams helfen und nötigenfalls korrigieren?

2020-11-22 12:59 UTC, alxndr-w reviewed
In der PR-Ansicht auf Github zerhaut es die Formatierung.

2020-11-22 13:12 UTC, TobiasKrais commented
Kannst du mir einen Screenshot schicken oder zeigen wie ich mir das anschauen kann? Ich weiß nicht, was du meinst oder wie ich das anzeigen lassen kann.

2020-11-22 14:09 UTC, alxndr-w commented
https://github.com/yakamara/redaxo_yform/pull/955/files?short_path=24b621f#diff-24b621fb15f0ef1c26133c6b5e50330e80cba0ee34c1799ce0667a2eb491d2e9

2020-11-22 20:34 UTC, TobiasKrais commented
Sieht bei mir gut aus. Ich denke, dass es genauso gedacht ist. Kannst du eventuell einen Screenshot machen in der der Fehler sichtbar ist.

2020-11-23 06:45 UTC, alxndr-w commented
Interessant, die Listen sieht jetzt gut aus, das war zum Zeitpunkt des Kommentars noch anders. Ich würde die Keys der objparams sowie deren Beispielwerte noch in Backtricks packen, sodass sie optisch besser vom Text zu unterscheiden sind. Und ein Codebeispiel fehlt auch noch.

2020-11-23 13:57 UTC, TobiasKrais commented
Oh, das sieht viel besser aus. Danke für den Tipp. Codebeispiel ist ja für die Methoden `getObjectparams` und `setObjectparams` direkt oberhalb zu finden. Sollte das nochmals explizit erwähnt werden?

2020-11-23 14:41 UTC, alxndr-w requested changes

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `actions`: Aktionen des Formulars
Dem Formular zugeordnete YForm-Actions

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `actions_executed`: Boolean. Wenn true sind die Aktionen ausgeführt. Siehe auch `preactions_executed` und `postactions_executed`.
Gibt an, ob YForm-Actions ausgeführt wurden `true` oder `false`

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `answertext`: Antworttext
Text, der nach erfolgreichem Absenden des Formulars mit oder anstelle des Formulars ausgegeben wird.

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `article_id`: Ziel Artikel ID des aFormulars
Artikel-ID, dessen URL als Ziel für das Formular dient

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `clang`: Sprach ID des Formulars
Clang-ID des Formulars (Sprache)

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `csrf_protection`: Boolean. Aktiviert den CSRF Schutz. Hierbei wird ein Cookie gesetzt.
(bitte auf Leerzeichen in Komposita achten, es heißt CSRF-Schutz, CSS-Klasse, YForm-Template, usw.)

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `main_id`: Datenbank Datensatz ID
optional: Primär-Schlüssel / ID des Datensatz, der bearbeitet wird.

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `form_data`: Formular in pipe Notation
Sicher?

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `form_anchor`: Sprunganker zu dem das Formular nach Absenden springt
(optional) ID des HTML-Sprungankers, um nach Absenden zu einem HTML-Element zu scrollen.

2020-11-23 14:41 UTC, alxndr-w commented on docs/formbuilder.md
> +- `form_method`: Sendemethode des Formulars: post oder get
Übertragungsweg des Formulars: `POST` (Standard) oder `GET`

2020-11-23 14:46 UTC, alxndr-w commented
> Codebeispiel ist ja für die Methoden getObjectparams und setObjectparams direkt oberhalb zu finden. Sollte das nochmals explizit erwähnt werden?

Mein Fehler, es wurde nur ein Ausschnitt der Datei gezeigt und desewgen habe ich den Kontext deiner Änderungen übersehen. Du hast natürlich recht.

2020-11-23 16:56 UTC, TobiasKrais commented on docs/formbuilder.md
> +- `form_data`: Formular in pipe Notation
Danach sieht es bei einem dump aus.

2020-11-23 16:59 UTC, TobiasKrais commented
Super. Danke. Hab alles übernommen.

2021-02-27 12:04 UTC, merged